name: HARD DEBUG

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: STEP 1 - CHECKOUT
        uses: actions/checkout@v4

      - name: STEP 2 - WHERE AM I
        run: pwd

      - name: STEP 3 - LIST FILES
        run: ls -la

      - name: STEP 4 - FIND BOT
        run: find .

      - name: STEP 5 - PYTHON
        run: python --version

      - name: STEP 6 - RUN FILE
        run: |
          echo "RUNNING BOT"
          python bot.py
