name: Gunluk Kripto Botu

on:
  workflow_dispatch: # Manuel tetikleme icin

jobs:
  run-bot: # Türkçe karakterleri temizledik, GitHub artık kızmayacak
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Bagimliliklari Yukle
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas feedparser

    - name: Botu Calistir
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        python bot.py
